config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'static_pages#home'
  get '/users', to: 'users#index'
  patch 'users/create_admin', to: 'users#create_admin', as: 'create_admin'
  patch 'users/remove_admin', to: 'users#remove_admin', as: 'remove_admin'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def require_admin_role
    unless current_user&.has_role?(:admin)
      flash[:alert]= "Access denied."
      redirect_back fallback_location: root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin_role, only: [:new, :create, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "#{@category.name} has been created"
    else
      flash.now[:alert] = 'Invalid Category name, or Category already exists.'
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category, notice: "#{@category.name} has been updated"
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: "#{@category.name} has been deleted"
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin_role

  def index
    @user_emails = User.pluck(:email)
  end

  def create_admin
    user = User.find(params[:user_id])
    user.add_role(:admin)
    redirect_to users_path, notice: "User #{user.email} has been made an Admin"
  end

  def remove_admin
    user = User.find(params[:user_id])
    user.remove_role(:admin)
    redirect_to users_path, notice: "User #{user.email} has had their Admin role removed"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category_form.html.erb
<div class="card card-list">
  <% if !@category.name.empty? %>
    <h1><%= @category.name %></h1>
  <% else %>
    <h1>Create a Category</h1>
  <% end %>

  <%= form_for @category do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="category-actions">
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <%= link_to "Cancel", categories_path, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/categories/_create.html.erb
<div class="card category-form">
  <h4>Create Category</h4>
  <%= form_for :category do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.submit "Create", class: "btn btn-dark"%>
    </div>

  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'categories/category_form' %>

app/views/categories/index.html.erb
<h1>Current Categories</h1>
<% if current_user.has_role?(:admin) %>
  <%= render 'categories/create' %>
<% end %>

<% @categories.each do |category| %>
  <div class="card card-list container">
    <div class="row">
      <div class="catgory-info col">
        <%= category.name %>
      </div>
      <div class="category-actions col">
        <%= link_to "View", category_path(category), class: "btn btn-dark" %>
        <% if current_user.has_role?(:admin) %>
          <%= button_to "Remove", category_path(category), method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render 'categories/category_form' %>

app/views/categories/show.html.erb
<div class="card card-list">
  <h1><%= @category.name %></h1>

  <% if current_user.has_role?(:admin) %>
    <div class="form-group category-actions">
      <%= link_to "Edit", edit_category_path(@category), class: "btn btn-dark " %>
      <%= button_to "Delete", category_path(@category), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this category?" } %>
    </div>
  <% end %>

  <%= link_to "Back to Categories", categories_path %>
</div>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success" role="alert"><%= notice %></p>
<% elsif alert %>
  <p class="alert alert-warning" role="alert"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">Footer Placeholder</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">tiddeR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-links" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/">Home</a></li>
              <li><a class="dropdown-item" href="/categories">Categories</a></li>
              <% if current_user.has_role? :admin %>
                <li><a class="dropdown-item" href="/users">Users</a></li>
              <%end %>
              <li><hr class="dropdown-divider"></li>
              <%= button_to "Logout", destroy_user_session_path, class:"nav-link", method: :delete %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          <%= link_to "Login", new_user_session_path, class:"nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="main-body">
    <%= render 'layouts/header' %>
    <div class="page-content">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="card home-banner">
  <h1>Welcome to teddiR</h1>
  <h4>The back-page of the Internet!</h4>
</div>




<!--<form class="login-form">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email Address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <button type="submit" class="btn btn-primary">Login</button>
  <%#= link_to "Create Account", static_pages_signup_path, class: "sign-up-link" %>
</form>-->

app/views/users/index.html.erb
<h1>Current Users</h1>

<% @user_emails.each do |email| %>
  <div class="card card-list">
    <%= email %>
    <% user = User.find_by(email: email) %>
    <% if user.email != current_user.email %>
      <% if user.has_role?(:admin) %>
        <%= button_to "Remove Admin", remove_admin_path(user_id: user.id), method: :patch, class: "admin-button"%>
      <% else %>
        <%= button_to "Create Admin", create_admin_path(user_id: user.id), method: :patch, class: "admin-button" %>
      <% end %>
    <% end %>
  </div>
<% end %>